.TH "Server.Program" 3 "Tue Sep 25 2018" "Relational Databases Assignment #1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Server.Program
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUser\fP (Socket client, List< \fBDataBase\fP > DataBaseTable)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Relational Databases Assignment #1 from the source code\&.
